# 2.3.6. Reduction

In [1]:
%pip install pandas 'numpy<2' --quiet

You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch


x = torch.arange(3, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [3]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [4]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [5]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [6]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [7]:
A.sum(axis=[0, 1]), A.sum()

(tensor(15.), tensor(15.))

In [8]:
A.mean(), A.sum()/A.numel()

(tensor(2.5000), tensor(2.5000))

In [9]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

# 2.3.7. Non-Reduction Sum

In [10]:
sum_A = A.sum(axis=1, keepdim=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [11]:
A.shape

torch.Size([2, 3])

In [12]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [13]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

# 2.3.8. Dot Products

In [14]:
y = torch.ones(3, dtype=torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [15]:
torch.sum(x*y)

tensor(3.)

# 2.3.9. Matrix–Vector Products

In [17]:
A, x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]))

In [16]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

# 2.3.10. Matrix–Matrix Multiplication

In [18]:
B = torch.ones(3, 4)
A.shape, B.shape

(torch.Size([2, 3]), torch.Size([3, 4]))

In [20]:
torch.dot(A, B)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [21]:
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

# 2.3.11. Norms

In [22]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [23]:
torch.abs(u).sum()

tensor(7.)

In [24]:
torch.norm(torch.ones(4, 9))

tensor(6.)