In [1]:
%pip install torch --quiet

You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


# 2.5.1. A Simple Function

In [2]:
import torch

In [3]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [4]:
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad  # The gradient is None by default

In [5]:
y = 2*torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [7]:
x.grad == 4*x

tensor([True, True, True, True])

In [8]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

# 2.5.2. Backward for Non-Scalar Variables

In [10]:
x.grad.zero_()
y = x*x
y.backward(gradient=torch.ones(len(y)))
x.grad


tensor([0., 2., 4., 6.])

# 2.5.3. Detaching Computation

In [12]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

In [13]:
x.grad == u

tensor([True, True, True, True])

# 2.5.4. Gradients and Python Control Flow

In [14]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [15]:
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

In [16]:
a.grad == d / a

tensor(True)